language: node_js
node_js:
  - '13'
dist: trusty
addons:
  chrome: stable
deploy:
  provider: heroku
  api_key:
    secure: Qg9zc0LQLPZ8JRBFev+l+6AI8K1Z2KYKMIUv7nwggkuIeBpf8fXtpYXTsz2/NtK0c4CnTpjg7cVxZLdhE2q/uzy85qq7PFEwQgZt97Jh57rF1ajYtLc76C5Z73lCQIV9r0eOSdfEZXtBJ6ES//j/8gZtEpxhkgt9W+vXJoNtjQTU9HnBhKL12reohxxChnlQJVAM1XkoQLnJrWlZ84NVjTJbzEuuZO3P0oD7B3ciFz5QHuPLBQFllI7i/EhxWqPobOGzgb91pDdp5FnBCQdRmxyZgW8mv64i1XX3q494GtUZyQUrAyO+9+knU7to4bGdQRutTECnTipbo2EQjjDu7ItGpeG9Z+E/MllUm6kEaXJnk6u7q3Qvf0j+kAv7dmvdXiwhMqmRKDC42KGSDlIJe1BTAHhYVBl2R+RbPGNSfSWtddeNzkta/z5sVaEXuWgQ+CynoeaCvDZ0783tscGUy5DDALeNEVak47fikrW5ErjOSiiTsH2GLO22glySQsxJS0jWd0tOOBFqxokNd1o6U2/I/MkUtpbfZuJrZrOJa98IasPukX8oGj+MbrIQ3nVD3H91ifFcVYSC++9pZjf9eThh0BmiSmqVqXQt+QHgz37ThCnNdx2FF0/uxEfSx8nhP613KIL7TV2iQPEr84EztUX07+ybA4RkaeT/Sk4KCKk=
  app: interviewon
notifications:
  email: false
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
